---
name: house-prices
channels:
  - conda-forge
dependencies:
  - python=3.9.6
  - pip
  - pip:
    - mlflow==1.18.0
    - pandas==1.3.1
    - scikit-learn==0.24.2
    - pyarrow==5.0.0
    - google-cloud-storage==1.41.1